import { IUiSettingBasedModuleMutationEven_Payload } from "../UiSettingBasedModuleMutationEvent/IUiSettingBasedModuleMutationEvent_Payload";

export interface IUiModuleManagerPassThroughEvent_Payload {
  ModuleMutationEvent_Payload: IUiSettingBasedModuleMutationEven_Payload
}