export enum MenuCommand {
    ScModeEdit,
    Unknown,
    MarkFavorite,
    CloseWindow,
    TakeSnapShot,
    AddCeTab,
    ScModeNormal,
    ScModePrev,
    Cancel,
    DrawStorage,
    Remove,
    RestoreState,
    UpdateNickname,
    QuickPublish,
    GoDesktop,
    GoContentEditor,
    PutAdminB
}
