export enum MsgFlag {
  Unknown,

  GetAllStorageOneWindow,
  NewWindowTest,
  RemoveFromStorage,
  ReqAddCETab,
  ReqAdminB,
  ReqCurState,
  ReqGoDesktop,
  ReqLoginWithAdminB,
  ReqOpenCE,
  ReqQuickPublish,
  ReqRestoreClick,
  ReqRestoreToNewTab,
  ReqSetScMode,
  ReqTakeSnapShot,
  ReqUpdateNickName,

  RespCurState,
  RespError,
  RespTaskFailed,
  RespTaskSuccessful,
  RespTest,
}